# Generated by Django 4.0.1 on 2022-01-08 02:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whereapp', '0002_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
