# Generated by Django 4.0.1 on 2022-01-08 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whereapp', '0003_search_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='date',
        ),
    ]
