# Generated by Django 4.0.1 on 2022-01-08 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whereapp', '0005_searchdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='searchdate',
            name='searchdate',
            field=models.DateField(blank=True),
        ),
    ]
